---

- hosts: all
  become: true
  gather_facts: no
  vars_files:
    - default_vars.yml
  
  pre_tasks:
    - name: Wake-on-LAN to PopOS Bench
      wakeonlan:
        mac: '70:5a:0f:31:8c:81'
        broadcast: 192.168.11.255
      delegate_to: localhost
      when: "'workstations' in group_names"
      changed_when: false

    - name: Wake-on-LAN to PopOS Bench
      wakeonlan:
        mac: '1c:4d:70:00:61:53'
        broadcast: 192.168.11.255
      delegate_to: localhost
      when: "'workstations' in group_names"
      changed_when: false

    - name: Wait for system to become reachable
      wait_for_connection:
        delay: 5
        timeout: 15
      when: "'workstations' in group_names"    
    
    - name: Gather facts for first time
      setup:

    - name: Installing Updates
      apt:
        upgrade: dist
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_distribution == 'Pop!_OS' or ansible_distribution == 'Ubuntu'

  tasks:
    - name: Installing Server Packages
      apt:
        name: "{{ server_apps }}"
        state: present
      when: ansible_distribution == 'Pop!_OS' or ansible_distribution == 'Ubuntu'

    # - name: Remove file (delete file)
    #   file:
    #     path: /home/nick/git/dotfiles/linux-dotfiles
    #     state: absent
        
    # - name: Remove file (delete file)
    #   file:
    #     path: /home/nick/.oh-my-zsh
    #     state: absent

    # - name: Remove file (delete file)
    #   file:
    #     path: /home/nick/.vimrc
    #     state: absent

    # - name: Remove file (delete file)
    #   file:
    #     path: /home/nick/.zshrc
    #     state: absent

    - name: Clone linux-dotfiles
      become_user: nick
      git:
        repo: https://github.com/crowsnesttech/linux-dotfiles.git
        dest: /home/nick/git/dotfiles/linux-dotfiles
        clone: yes
        update: yes

    - name: Clone oh-my-zsh
      become_user: nick
      git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: /home/nick/git/dotfiles/linux-dotfiles/.oh-my-zsh
        clone: yes
        update: yes

    - name: Symbolic link to oh-my-zsh
      file:
        src: /home/nick/git/dotfiles/linux-dotfiles/.oh-my-zsh
        dest: /home/nick/.oh-my-zsh
        owner: nick
        group: nick
        state: link
        force: yes

    - name: Symbolic link to vimrc
      file:
        src: /home/nick/git/dotfiles/linux-dotfiles/.vimrc
        dest: /home/nick/.vimrc
        owner: nick
        group: nick
        state: link
        force: yes

    - name: Symbolic link to zshrc
      file:
        src: /home/nick/git/dotfiles/linux-dotfiles/.zshrc
        dest: /home/nick/.zshrc
        owner: nick
        group: nick
        state: link
        force: yes

    - name: Symbolic link to tmux
      file:
        src: /home/nick/git/dotfiles/linux-dotfiles/.tmux.conf
        dest: /home/nick/.tmux.com
        owner: nick
        group: nick
        state: link
        force: yes

    - name: Clone zsh-autosuggestions
      become_user: nick
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: /home/nick/.oh-my-zsh/custom/plugins/zsh-autosuggestions
        clone: yes
        update: yes

    - name: Clone zsh-syntax-highlighting
      become_user: nick
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: /home/nick/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
        clone: yes
        update: yes

    - name: Copy custom ZSH theme
      copy:
        src: /home/nick/git/dotfiles/linux-dotfiles/agnostercstm.zsh-theme
        dest: /home/nick/git/dotfiles/linux-dotfiles/.oh-my-zsh/custom/themes/
        owner: nick
        group: nick
        mode: '755'

    - name: Change user Shell to ZSH 
      become: yes
      user:
        name: nick
        shell: /bin/zsh
      changed_when: false

    # - name: Clone a github repository
    #   become_user: nick
    #   git:
    #     repo: https://github.com/crowsnesttech/install-dotfiles.git
    #     dest: /home/nick/install-dotfiles/
    #     clone: yes
    #     update: yes

    # - name: Copy and Execute the script
    #   become_user: nick
    #   script: ~/git/dotfiles/install-dotfiles/linux-zsh.sh  
      
    # changed_when: false      
    # - name: zshrc
    #   copy:
    #     src: files/zshrc
    #     dest: /home/nick/.zshrc
    #     owner: nick
    #     group: nick
    #     mode: "0775"
    
    # - name: vimrc  
    #   copy:
    #     src: files/vimrc
    #     dest: /home/nick/.vimrc
    #     owner: nick
    #     group: nick
    #     mode: "0775"

    # - name: Clone ohmyzsh
    #   become_user: nick
    #   git:
    #     repo: https://github.com/ohmyzsh/ohmyzsh.git
    #     dest: /home/nick/.oh-my-zsh
    #     single_branch: yes
    #     version: main

    # - name: clone zsh-autosuggestions  
    #   git:
    #     repo: https://github.com/zsh-users/zsh-autosuggestions.git
    #     dest: /home/nick/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    #     single_branch: yes
    #     version: main
    #     #update: yes
    
    # - name: clone zsh-syntax-highlighting
    #   git:
    #     repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    #     dest: /home/nick/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    #     single_branch: yes
    #     version: main
        
    # - name: add ansible user
    #   user:
    #     name: ansibleuser
    #     system: yes

    # - name: set up sudo for ansible user
    #   copy:
    #     src: files/sudoer_ansibleuser
    #     dest: /etc/sudoers.d/ansibleuser
    #     owner: root
    #     group: root
    #     mode: 0440

    # - name: add ansible-pull cron job
    #   cron:
    #     name: ansible auto-provision
    #     user: ansibleuser
    #     minute: "*/10"
    #     job: ansible-pull -o -U https://github.com/crowsnesttech/ansible_linux.git