---

- name: Installing Base Packages
  apt:
    name: "{{ base_apps }}"
    state: present
  when: ansible_os_family == 'Debian'

- name: Clone linux-dotfiles
  become_user: nick
  git:
    repo: https://github.com/crowsnesttech/linux-dotfiles.git
    dest: /home/nick/git/dotfiles/linux-dotfiles
    clone: yes
    update: yes
    force: yes

- name: Clone oh-my-zsh
  become_user: nick
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: /home/nick/git/dotfiles/linux-dotfiles/.oh-my-zsh
    clone: yes
    update: yes

- name: Symbolic link to oh-my-zsh
  file:
    src: /home/nick/git/dotfiles/linux-dotfiles/.oh-my-zsh
    dest: /home/nick/.oh-my-zsh
    owner: nick
    group: nick
    state: link
    force: yes

- name: Symbolic link to vimrc
  file:
    src: /home/nick/git/dotfiles/linux-dotfiles/.vimrc
    dest: /home/nick/.vimrc
    owner: nick
    group: nick
    state: link
    force: yes

- name: Symbolic link to zshrc
  file:
    src: /home/nick/git/dotfiles/linux-dotfiles/.zshrc
    dest: /home/nick/.zshrc
    owner: nick
    group: nick
    state: link
    force: yes

- name: Symbolic link to tmux
  file:
    src: /home/nick/git/dotfiles/linux-dotfiles/.tmux.conf
    dest: /home/nick/.tmux.com
    owner: nick
    group: nick
    state: link
    force: yes

- name: Clone zsh-autosuggestions
  become_user: nick
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: /home/nick/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    clone: yes
    update: yes

- name: Clone zsh-syntax-highlighting
  become_user: nick
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: /home/nick/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    clone: yes
    update: yes

- name: Copy custom ZSH theme
  copy:
    src: /home/nick/git/dotfiles/linux-dotfiles/agnostercstm.zsh-theme
    dest: /home/nick/git/dotfiles/linux-dotfiles/.oh-my-zsh/custom/themes/
    owner: nick
    group: nick
    mode: '755'

- name: Change user Shell to ZSH 
  become: yes
  user:
    name: nick
    shell: /bin/zsh
  changed_when: false