---

workstation_apps:
  - snapd
  - ffmpeg
  - handbrake
  - neofetch
  - youtube-dl
  - syncthing
  - timeshift
  - gnome-sushi
  - remmina
  - mpv
# workstation_flatpaks:
#   - com.bitwarden.desktop

# workstation_snaps:
#   - joplin-james-carroll
