---

- name: Installing Workstation Packages
  apt:
    name: "{{ workstation_apps }}"
    state: present
  when: ansible_os_family == 'Debian'

- name: Install apt-transport-https
  apt:
    state: latest
  when: ansible_os_family == 'Debian'

- name: Add Apt signing key
  apt_key:
    url: "https://dl.google.com/linux/linux_signing_key.pub"
    state: present
  when: ansible_os_family == 'Debian'

- name: Add repository into sources list
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google-chrome
  when: ansible_os_family == 'Debian'

- name: Install google-chrome-stable
  apt:
    name: "google-chrome-stable"
    state: latest
  when: ansible_os_family == 'Debian'

- name: Copy and Execute the script 
  script: files/nerd-fonts/install.sh